import { generateAIWorkoutPlan, type AIPlanParams } from '../../services/aiPlanService';
import { Equipment } from '../../types/exercise';

// Mock plan data
const MOCK_PLAN = {
  id: 'ai-test-hypertrophy-4day',
  name: 'AI Hypertrophy 4-Day Split',
  nameRo: 'Split 4 Zile Hipertrofie AI',
  description: 'A science-backed 4-day hypertrophy programme generated by AI.',
  descriptionRo: 'Program de 4 zile bazat pe știință, generat de AI.',
  level: 'intermediate',
  daysPerWeek: 4,
  category: 'hypertrophy',
  createdBy: 'AI',
  weeks: [
    {
      weekNumber: 1,
      days: [
        { dayNumber: 1, name: 'Push Day', exercises: [{ exerciseId: 'bench-press', sets: 4, reps: 10, restSeconds: 90 }, { exerciseId: 'overhead-press', sets: 3, reps: 10, restSeconds: 90 }, { exerciseId: 'lateral-raise', sets: 4, reps: 15, restSeconds: 60 }] },
        { dayNumber: 2, name: 'Pull Day', exercises: [{ exerciseId: 'barbell-row', sets: 4, reps: 10, restSeconds: 90 }, { exerciseId: 'lat-pulldown', sets: 3, reps: 12, restSeconds: 60 }] },
        { dayNumber: 3, name: 'Leg Day', exercises: [{ exerciseId: 'squat', sets: 4, reps: 8, restSeconds: 120 }, { exerciseId: 'romanian-deadlift', sets: 3, reps: 10, restSeconds: 90 }] },
        { dayNumber: 4, name: 'Upper Body', exercises: [{ exerciseId: 'incline-bench', sets: 3, reps: 12, restSeconds: 90 }, { exerciseId: 'cable-row', sets: 3, reps: 12, restSeconds: 60 }] },
      ],
    },
    { weekNumber: 2, days: [{ dayNumber: 1, name: 'Push Day', exercises: [{ exerciseId: 'bench-press', sets: 4, reps: 10, restSeconds: 90 }] }, { dayNumber: 2, name: 'Pull Day', exercises: [{ exerciseId: 'barbell-row', sets: 4, reps: 10, restSeconds: 90 }] }, { dayNumber: 3, name: 'Leg Day', exercises: [{ exerciseId: 'squat', sets: 4, reps: 8, restSeconds: 120 }] }, { dayNumber: 4, name: 'Upper Body', exercises: [{ exerciseId: 'incline-bench', sets: 4, reps: 10, restSeconds: 90 }] }] },
    { weekNumber: 3, days: [{ dayNumber: 1, name: 'Push Day', exercises: [{ exerciseId: 'bench-press', sets: 5, reps: 8, restSeconds: 90 }] }, { dayNumber: 2, name: 'Pull Day', exercises: [{ exerciseId: 'barbell-row', sets: 5, reps: 8, restSeconds: 90 }] }, { dayNumber: 3, name: 'Leg Day', exercises: [{ exerciseId: 'squat', sets: 5, reps: 6, restSeconds: 120 }] }, { dayNumber: 4, name: 'Upper Body', exercises: [{ exerciseId: 'incline-bench', sets: 4, reps: 10, restSeconds: 90 }] }] },
    { weekNumber: 4, days: [{ dayNumber: 1, name: 'Push Day', exercises: [{ exerciseId: 'bench-press', sets: 5, reps: 8, restSeconds: 90 }] }, { dayNumber: 2, name: 'Pull Day', exercises: [{ exerciseId: 'barbell-row', sets: 5, reps: 8, restSeconds: 90 }] }, { dayNumber: 3, name: 'Leg Day', exercises: [{ exerciseId: 'squat', sets: 5, reps: 6, restSeconds: 120 }] }, { dayNumber: 4, name: 'Upper Body', exercises: [{ exerciseId: 'incline-bench', sets: 5, reps: 8, restSeconds: 90 }] }] },
  ],
};

// Mock the AI server client — services proxy through the backend, not Anthropic directly
jest.mock('../../services/aiServerClient', () => ({
  streamAI: jest.fn(),
}));

import { streamAI } from '../../services/aiServerClient';
const mockStreamAI = streamAI as jest.MockedFunction<typeof streamAI>;

// ─── Default params ───────────────────────────────────────────────────────────

const DEFAULT_PARAMS: AIPlanParams = {
  goal: 'build_muscle',
  experience: 'intermediate',
  daysPerWeek: 4,
  equipment: [Equipment.Barbell, Equipment.Dumbbell, Equipment.Cable],
};

// ─── Tests ────────────────────────────────────────────────────────────────────

beforeEach(() => {
  jest.clearAllMocks();
  mockStreamAI.mockImplementation(async (_endpoint, _body, onChunk) => {
    const text = JSON.stringify(MOCK_PLAN);
    onChunk?.(text);
    return text;
  });
});

describe('generateAIWorkoutPlan', () => {
  it('returns a valid WorkoutPlan for standard params', async () => {
    const plan = await generateAIWorkoutPlan(DEFAULT_PARAMS);

    expect(plan.name).toBeTruthy();
    expect(plan.level).toBe('intermediate');
    expect(plan.daysPerWeek).toBe(4);
    expect(plan.weeks).toHaveLength(4);
    expect(plan.createdBy).toBe('AI');
  });

  it('each week has exactly daysPerWeek training days', async () => {
    const plan = await generateAIWorkoutPlan(DEFAULT_PARAMS);
    plan.weeks.forEach((week) => {
      expect(week.days.length).toBeLessThanOrEqual(DEFAULT_PARAMS.daysPerWeek);
      expect(week.days.length).toBeGreaterThan(0);
    });
  });

  it('exercises have required fields', async () => {
    const plan = await generateAIWorkoutPlan(DEFAULT_PARAMS);
    const day1 = plan.weeks[0].days[0];
    day1.exercises.forEach((ex) => {
      expect(ex.exerciseId).toBeTruthy();
      expect(ex.sets).toBeGreaterThan(0);
      expect(ex.reps).toBeGreaterThanOrEqual(0);
      expect(ex.restSeconds).toBeGreaterThan(0);
    });
  });

  it('calls streamAI with /ai/workout-plan endpoint', async () => {
    await generateAIWorkoutPlan(DEFAULT_PARAMS);
    expect(mockStreamAI).toHaveBeenCalledWith(
      '/ai/workout-plan',
      expect.objectContaining({ prompt: expect.any(String) }),
      undefined,
      120_000,
    );
  });

  it('passes prompt containing goal and equipment info', async () => {
    await generateAIWorkoutPlan(DEFAULT_PARAMS);
    const calledBody = mockStreamAI.mock.calls[0][1];
    const prompt = calledBody.prompt as string;
    expect(prompt).toContain('hypertrophy');
    expect(prompt).toContain('barbell');
  });

  it('invokes onProgress callback with streamed text', async () => {
    const onProgress = jest.fn();
    await generateAIWorkoutPlan(DEFAULT_PARAMS, onProgress);
    expect(onProgress).toHaveBeenCalled();
    // The mock emits the entire JSON as one chunk
    const combinedArgs = onProgress.mock.calls.map(([c]: [string]) => c).join('');
    expect(combinedArgs.length).toBeGreaterThan(0);
  });

  it('generates plan name from goal when building muscle', async () => {
    const plan = await generateAIWorkoutPlan({ ...DEFAULT_PARAMS, goal: 'build_muscle' });
    expect(plan.name).toBeTruthy();
    expect(typeof plan.name).toBe('string');
  });

  it('throws on invalid JSON from stream', async () => {
    mockStreamAI.mockResolvedValueOnce('this is not json at all');
    await expect(generateAIWorkoutPlan(DEFAULT_PARAMS)).rejects.toThrow();
  });

  it('throws when AI response has no JSON object', async () => {
    mockStreamAI.mockResolvedValueOnce('Claude says: hello world!');
    await expect(generateAIWorkoutPlan(DEFAULT_PARAMS)).rejects.toThrow(
      'No JSON object found in AI response',
    );
  });

  it('strips markdown code fences from response', async () => {
    const fencedText = '```json\n' + JSON.stringify(MOCK_PLAN) + '\n```';
    mockStreamAI.mockResolvedValueOnce(fencedText);

    const plan = await generateAIWorkoutPlan(DEFAULT_PARAMS);
    expect(plan.name).toBeTruthy();
    expect(plan.weeks).toHaveLength(4);
  });

  it('fills default id when AI omits it', async () => {
    const planNoId = { ...MOCK_PLAN, id: undefined };
    mockStreamAI.mockResolvedValueOnce(JSON.stringify(planNoId));

    const plan = await generateAIWorkoutPlan(DEFAULT_PARAMS);
    expect(plan.id).toMatch(/^ai-plan-\d+/);
  });

  it('re-throws API errors from the stream', async () => {
    mockStreamAI.mockRejectedValueOnce(new Error('Rate limit exceeded'));
    await expect(generateAIWorkoutPlan(DEFAULT_PARAMS)).rejects.toThrow('Rate limit exceeded');
  });
});

describe('useWorkoutStore — saved plans', () => {
  // Import after mocks are established
  let useWorkoutStore: typeof import('../../stores/useWorkoutStore').useWorkoutStore;

  beforeEach(async () => {
    jest.resetModules();

    // Re-apply mocks after resetModules
    jest.mock('../../services/aiServerClient', () => ({
      streamAI: jest.fn(),
    }));

    const mod = await import('../../stores/useWorkoutStore');
    useWorkoutStore = mod.useWorkoutStore;
    useWorkoutStore.setState({ savedPlans: [] });
  });

  const makePlan = (id: string) =>
    ({
      id,
      name: `Plan ${id}`,
      nameRo: `Plan ${id}`,
      description: 'Test',
      descriptionRo: 'Test',
      level: 'intermediate' as const,
      daysPerWeek: 4,
      category: 'hypertrophy',
      createdBy: 'AI',
      weeks: [],
    });

  it('saves a generated plan', () => {
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p1'));
    expect(useWorkoutStore.getState().savedPlans).toHaveLength(1);
    expect(useWorkoutStore.getState().savedPlans[0].id).toBe('p1');
  });

  it('prepends new plans (most recent first)', () => {
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p1'));
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p2'));
    expect(useWorkoutStore.getState().savedPlans[0].id).toBe('p2');
  });

  it('replaces a plan with the same id', () => {
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p1'));
    const updated = { ...makePlan('p1'), name: 'Updated Plan' };
    useWorkoutStore.getState().saveGeneratedPlan(updated);
    const plans = useWorkoutStore.getState().savedPlans;
    expect(plans).toHaveLength(1);
    expect(plans[0].name).toBe('Updated Plan');
  });

  it('removes a generated plan by id', () => {
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p1'));
    useWorkoutStore.getState().saveGeneratedPlan(makePlan('p2'));
    useWorkoutStore.getState().removeGeneratedPlan('p1');
    const plans = useWorkoutStore.getState().savedPlans;
    expect(plans).toHaveLength(1);
    expect(plans[0].id).toBe('p2');
  });

  it('does not throw when removing non-existent plan', () => {
    expect(() => useWorkoutStore.getState().removeGeneratedPlan('does-not-exist')).not.toThrow();
  });
});
